Dependencies:
- 'on': ['Linux', 'FreeBSD', 'Windows', 'macOS']
  'require':
    'frameworks/extra-cmake-modules': '@latest'
    'frameworks/kconfig' : '@latest'
    'frameworks/kwindowsystem' : '@latest'
    'frameworks/kcoreaddons' : '@latest'

Options:
  test-before-installing: True
  require-passing-tests-on: [ 'Linux', 'FreeBSD' ]
