// Getting the highest scored caches for (application/agent, activity)

select distinct ?resource,
   (
       (
           ?lastScore * bif:exp(-
               bif:datediff('day', ?lastUpdate, ##CURRENT_DATETIME##)
           )
       )
   as ?score) where {
     ?cache kext:targettedResource ?resource .
     ?cache a kext:ResourceScoreCache .
     ?cache nao:lastModified ?lastUpdate .
     ?cache kext:cachedScore ?lastScore .
     ?cache kext:usedActivity ##ACTIVITY## .
     ?cache kext:initiatingAgent ##AGENT## .
     OPTIONAL { ?resource nie:url ?uri . } .
}
ORDER BY DESC (?score)
LIMIT 10

// Getting the highest scored caches for (activity)

select distinct ?resource,
    (
        (
            SUM (
                ?lastScore * bif:exp(
                    - bif:datediff('day', ?lastUpdate, ##CURRENT_DATETIME##)
                )
            )
        )
        as ?score
    ) where {
        ?cache kext:targettedResource ?resource .
        ?cache a kext:ResourceScoreCache .
        ?cache nao:lastModified ?lastUpdate .
        ?cache kext:cachedScore ?lastScore .
        ?cache kext:usedActivity ##ACTIVITY## .
    }
    GROUP BY (?resource)
    ORDER BY DESC (?score)
    LIMIT 10

// get score caches

select ?e, ?agent, ?r, ?score where {
     ?e a kext:ResourceScoreCache .
     ?e kext:cachedScore ?score .
     ?e kext:initiatingAgent ?agentRes . ?agentRes nao:identifier ?agent .
     ?e kext:targettedResource ?rRes . ?rRes nie:url ?r .
}

// des

select ?e, ?agent, ?r where {
     ?e a nuao:DesktopEvent .
     ?e nuao:initiatingAgent ?agentRes . ?agentRes nao:identifier ?agent .
     ?e nuao:targettedResource ?rRes . ?rRes nie:url ?r
}

// activities
select ?activityName, ?activityId, ?activity where { ?activity a kext:Activity . ?activity nao:prefLabel ?activityName . ?activity kext:activityIdentifier ?activityId . }

// score caches
select ?resourceUri, ?score where { ?cache a kext:ResourceScoreCache . ?cache kext:targettedResource ?resource . ?resource nie:url ?resourceUri . ?cache kext:cachedScore ?score . }

