#ifndef CONFIG_FEATURES_H_
#define CONFIG_FEATURES_H_

#cmakedefine01 HAVE_NEPOMUK

#cmakedefine KAMD_DATA_DIR "@KAMD_DATA_DIR@"

#cmakedefine01 HAVE_CXX11_AUTO
#cmakedefine01 HAVE_CXX11_NULLPTR
#cmakedefine01 HAVE_CXX11_LAMBDA
#cmakedefine01 HAVE_CXX11_OVERRIDE
#cmakedefine01 HAVE_CXX_OVERRIDE_ATTR

#endif
